[platformio]
default_envs = transmitter, receiver

[env]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = jgromes/RadioLib@7.7.1
build_flags = -Wall -Wextra

[env:transmitter]
build_flags = ${env.build_flags} -DPIXELLINK_TX=1

[env:receiver]
build_flags = ${env.build_flags} -DPIXELLINK_TX=0
